/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "PUSH_BUTTON_INPUT.h"
#include "PUSH_BUTTON_INPUT_aliases.h"
#include "SUPPLY_ENABLE.h"
#include "SUPPLY_ENABLE_aliases.h"
#include "PWM.h"
#include "PWM_OUTPUT.h"
#include "PWM_OUTPUT_aliases.h"
#include "PWM_CLOCK.h"
#include "PWM_isr.h"
#include "Push_Button_isr.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

