/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PUSH_BUTTON_INPUT.h"
#include "PUSH_BUTTON_INPUT_aliases.h"
#include "SUPPLY_ENABLE.h"
#include "SUPPLY_ENABLE_aliases.h"
#include "PWM.h"
#include "PWM_OUTPUT.h"
#include "PWM_OUTPUT_aliases.h"
#include "PWM_CLOCK.h"
#include "PWM_isr.h"
#include "Push_Button_isr.h"
#include "Mode.h"
#include "Mode_aliases.h"
#include "B.h"
#include "B_aliases.h"
#include "G.h"
#include "G_aliases.h"
#include "R.h"
#include "R_aliases.h"
#include "Time_Bit_0.h"
#include "Time_Bit_0_aliases.h"
#include "Time_Bit_1.h"
#include "Time_Bit_1_aliases.h"
#include "Time_Bit_2.h"
#include "Time_Bit_2_aliases.h"
#include "Time_Bit_3.h"
#include "Time_Bit_3_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

